#/**
# * \u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u5916\u90e8\u74b0\u5883\u5b9a\u7fa9\u30ea\u30bd\u30fc\u30b9\u3067\u3059\u3002<br>
# * 
# * @author Kitagawa<br>
# * 
# *<!--
# * \u66f4\u65b0\u65e5		\u66f4\u65b0\u8005			\u66f4\u65b0\u5185\u5bb9
# * 2026/03/30	Kitagawa		\u65b0\u898f\u4f5c\u6210
# *-->
# */
# -------------------------------------------------------------
# \u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u5171\u901a\u52d5\u4f5c\u5b9a\u7fa9
# -------------------------------------------------------------
# \u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u30c6\u30fc\u30de(dark/light)
application.theme=dark

# \u30ef\u30fc\u30af\u30b9\u30da\u30fc\u30b9\u30ea\u30dd\u30b8\u30c8\u30ea\u30d1\u30b9
application.repository.path=./repos

# Web\u30a4\u30f3\u30bf\u30d5\u30a7\u30fc\u30b9\u30b5\u30fc\u30d0\u30fc\u30dd\u30fc\u30c8
application.webui.port=8080

# Web\u30a4\u30f3\u30bf\u30d5\u30a7\u30fc\u30b9\u30b5\u30fc\u30d0\u30fc\u540c\u6642\u63a5\u7d9a\u6570
application.webui.connection=256

# -------------------------------------------------------------
# \u30a8\u30fc\u30b8\u30a7\u30f3\u30c8\u5171\u901a\u52d5\u4f5c\u5b9a\u7fa9
# -------------------------------------------------------------
# \u30a8\u30fc\u30b8\u30a7\u30f3\u30c8\u51e6\u7406\u5b9f\u884c\u6642\u30bf\u30a4\u30e0\u30a2\u30a6\u30c8(\u79d2)
agent.timeout=3600

# -------------------------------------------------------------
# Claude Code CLI
# -------------------------------------------------------------
# CLI\u8d77\u52d5\u30b3\u30de\u30f3\u30c9\u6587\u5b57\u5217
agent.cli.claude-cli.command=%APPDATA%\\npm\\claude.cmd
#agent.cli.claude-cli.command=%USERPROFILE%\\.local\\bin\\claude.exe

# -------------------------------------------------------------
# Gemini CLI
# -------------------------------------------------------------
# CLI\u8d77\u52d5\u30b3\u30de\u30f3\u30c9\u6587\u5b57\u5217
agent.cli.gemini-cli.command=%APPDATA%\\npm\\gemini.cmd

# -------------------------------------------------------------
# Codex CLI
# -------------------------------------------------------------
# CLI\u8d77\u52d5\u30b3\u30de\u30f3\u30c9\u6587\u5b57\u5217
agent.cli.codex-cli.command=%APPDATA%\\npm\\codex.cmd

# -------------------------------------------------------------
# GitHub Copilot CLI
# -------------------------------------------------------------
# CLI\u8d77\u52d5\u30b3\u30de\u30f3\u30c9\u6587\u5b57\u5217
agent.cli.copilot-cli.command=%APPDATA%\\npm\\copilot.cmd
